# Generated by Django 4.1 on 2022-09-28 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0010_candidate_info_remove_applying_candidate_vid_and_more'),
        ('login', '0002_alter_apply_candiate_login_cid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply_candiate_login',
            name='cid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.candidate_info'),
        ),
    ]
