# Generated by Django 4.1 on 2022-09-26 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employeedetail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='designation',
            name='dept_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='employeedetail.department'),
            preserve_default=False,
        ),
    ]
