# Generated by Django 4.1 on 2022-09-30 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employeedetail', '0002_designation_dept_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp_detail',
            name='cid',
        ),
        migrations.RemoveField(
            model_name='emp_detail',
            name='dept_id',
        ),
        migrations.RemoveField(
            model_name='emp_detail',
            name='designation',
        ),
        migrations.AddField(
            model_name='emp_detail',
            name='designation_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='employeedetail.designation'),
            preserve_default=False,
        ),
    ]
