# Generated by Django 4.1 on 2022-09-30 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeedetail', '0003_remove_emp_detail_cid_remove_emp_detail_dept_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp_detail',
            name='special_role',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
