# Generated by Django 4.1 on 2022-09-13 09:50

from django.db import migrations, models
import django.db.models.deletion
import recruitment.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='applying_candidate',
            fields=[
                ('cid', models.IntegerField(default='-', primary_key=True, serialize=False)),
                ('vid', models.IntegerField(default='-', unique=True)),
                ('name', models.CharField(default='-', max_length=50)),
                ('contact', models.IntegerField(default=0, unique=True, validators=[recruitment.models.validate_number])),
                ('position', models.CharField(default='-', max_length=50)),
                ('age', models.CharField(default='-', max_length=50)),
                ('mail', models.EmailField(max_length=50, unique=True, validators=[recruitment.models.validate_email])),
                ('gender', models.CharField(default='-', max_length=50)),
                ('cv', models.ImageField(default='-', upload_to='images/')),
                ('sheet_no', models.CharField(default='-', max_length=10)),
                ('status', models.CharField(default='-', max_length=10)),
                ('addharcard_no', models.IntegerField(default=0, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='vaacancy',
            fields=[
                ('vid', models.IntegerField(default='-', primary_key=True, serialize=False)),
                ('designeation_id', models.IntegerField(default='-')),
                ('dept_id', models.IntegerField(default='-')),
                ('designeation', models.CharField(default='-', max_length=50)),
                ('salary', models.CharField(default='-', max_length=50)),
                ('skill', models.CharField(default='-', max_length=50)),
                ('experience', models.CharField(default='-', max_length=50)),
                ('no_of_vacancy', models.CharField(default='-', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='assesment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='-', max_length=20)),
                ('apptitute', models.IntegerField(default='-')),
                ('codeing', models.IntegerField(default='-')),
                ('interview1', models.IntegerField(default='-')),
                ('interview2', models.IntegerField(default='-')),
                ('result', models.CharField(default='-', max_length=50)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.applying_candidate')),
            ],
        ),
    ]
