# Generated by Django 4.1 on 2022-09-26 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employeedetail', '0002_designation_dept_id'),
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaacancy',
            name='dept_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeedetail.department'),
        ),
        migrations.AlterField(
            model_name='vaacancy',
            name='designeation_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeedetail.designation'),
        ),
    ]
