# Generated by Django 4.1 on 2022-09-26 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_remove_vaacancy_designeation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaacancy',
            name='dept_id',
        ),
    ]
