# Generated by Django 4.1 on 2022-09-27 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0004_remove_vaacancy_dept_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applying_candidate',
            name='position',
        ),
    ]
