# Generated by Django 4.1 on 2022-09-28 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0005_remove_applying_candidate_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applying_candidate',
            name='cv',
        ),
    ]
