# Generated by Django 4.1 on 2022-09-28 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0007_alter_applying_candidate_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applying_candidate',
            name='vid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.vaacancy'),
        ),
    ]
