# Generated by Django 4.1 on 2022-09-28 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0008_alter_applying_candidate_vid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaacancy',
            name='vid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
