# Generated by Django 4.1 on 2022-09-28 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0009_alter_vaacancy_vid'),
    ]

    operations = [
        migrations.CreateModel(
            name='candidate_info',
            fields=[
                ('cid', models.IntegerField(default='-', primary_key=True, serialize=False)),
                ('name', models.CharField(default='-', max_length=50)),
                ('contact', models.IntegerField(default=0, unique=True)),
                ('age', models.CharField(default='-', max_length=50)),
                ('mail', models.EmailField(max_length=50, unique=True)),
                ('gender', models.CharField(default='-', max_length=50)),
                ('sheet_no', models.CharField(default='-', max_length=10)),
                ('status', models.CharField(default='-', max_length=10)),
                ('addharcard_no', models.IntegerField(default=0, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='applying_candidate',
            name='vid',
        ),
        migrations.CreateModel(
            name='applying',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.vaacancy')),
            ],
        ),
        migrations.AlterField(
            model_name='assesment',
            name='cid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.candidate_info'),
        ),
    ]
