# Generated by Django 4.1 on 2022-09-28 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0010_candidate_info_remove_applying_candidate_vid_and_more'),
        ('login', '0003_alter_apply_candiate_login_cid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='applying_candidate',
        ),
    ]
