# Generated by Django 4.1 on 2022-09-28 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0011_delete_applying_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='applying',
            name='cid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='recruitment.candidate_info'),
            preserve_default=False,
        ),
    ]
